const COMMENT_DEPTH_MAX = 2;
const COMMENT_PAGE_SIZE_DEFAULT = 10;
const COMMENT_PAGE_SIZE_MAX = 30;
const COMMENT_EDIT_WINDOW_MS = 1000 * 60 * 30;
const COMMENT_SESSION_TTL_HOURS = 24 * 14;
const COMMENT_ACTOR_COOKIE = 'ff_comment_actor';

const COMMENT_MEDIA_TYPE = {
  IMAGE: 'image',
  GIF: 'gif',
};

const COMMENT_REACTION_TYPE = {
  HEART: 'heart',
  THUMBS_UP: 'thumbs_up',
  EYES: 'eyes',
  MELT: 'melt',
  QUESTION: 'question',
};

const COMMENT_REACTION_LIST = [
  COMMENT_REACTION_TYPE.HEART,
  COMMENT_REACTION_TYPE.THUMBS_UP,
  COMMENT_REACTION_TYPE.EYES,
  COMMENT_REACTION_TYPE.MELT,
  COMMENT_REACTION_TYPE.QUESTION,
];

module.exports = {
  COMMENT_DEPTH_MAX,
  COMMENT_PAGE_SIZE_DEFAULT,
  COMMENT_PAGE_SIZE_MAX,
  COMMENT_EDIT_WINDOW_MS,
  COMMENT_SESSION_TTL_HOURS,
  COMMENT_ACTOR_COOKIE,
  COMMENT_MEDIA_TYPE,
  COMMENT_REACTION_TYPE,
  COMMENT_REACTION_LIST,
};
